vendor/sdl2: add static libraries for Linux
odin-lang/Odin pull request #1318
Opened 2021-11-19 10:40 UTC by ftphikari

SDL bindings assume the latest version of libraries, however most Linux
distributions only supply tagged versions, the last of which for ttf is more
than 2 years old.

This commit adds compiled Linux/glibc libraries for all SDL modules.

2021-11-19 10:59 UTC, gingerBill commented on vendor/sdl2/image/sdl_image.odin
> +	@require foreign import "system:pthread"
If you are wanting to do this, you need to write it like this:
```odin
foreign import lib {
	"linux-SDL2_image.a",
	"system:dl",
	"system:pthread",
}
```

2021-11-19 10:59 UTC, gingerBill commented on vendor/sdl2/image/sdl_image.odin
> +	@require foreign import "system:pthread"
Same with every other instance of these imports.

2021-11-19 11:02 UTC, gingerBill requested changes
SDL2 should not use static libraries for Linux for numerous reasons, and the SDL team recommend people dynamically linking to SDL.

2021-11-19 12:33 UTC, ftphikari commented
> SDL2 should not use static libraries for Linux for numerous reasons, and the SDL team recommend people dynamically linking to SDL.

That is what they say. I don't necessarily agree, since they broke the behavior of programs in the past. I don't want my program to work one way, and then not work differently when they release a new version. Still, they themselves provide the build script to compile a static library, which is what i did. And this static library has an option to be overwritten by a dynamic one at run-time by using a special environment variable.

So should we really care about what they say in light of those reasons? Or does portability of an executable matters more?

2021-11-23 20:46 UTC, ftphikari commented
Since we agreed to have shared libs on Linux and to use workarounds for now, i'm closing this.

2021-11-23 20:46 UTC, closed without merging