`matrix2x2_inverse`: Added missing `-, +` signs to the function
odin-lang/Odin pull request #1429
Opened 2022-01-14 19:51 UTC by bytesiz3d

Closes #1428

2022-01-14 20:02 UTC, Kelimion commented
That would make it the same as `matrix2x2_inverse_transpose`?

2022-01-20 13:11 UTC, bytesiz3d commented
There's a difference in element order between `matrix2x2_inverse_transpose` and `matrix2x2_inverse`

2022-01-20 13:15 UTC, gingerBill requested changes

2022-01-20 13:15 UTC, gingerBill commented on core/runtime/core_builtin_matrix.odin
> +		y[1, 1] = +x[0, 0] * id
This should be this:
```odin
It should be this:
```
		y[0, 0] = +x[1, 1] / d
		y[0, 1] = -x[0, 1] / d
		y[1, 0] = -x[1, 0] / d
		y[1, 1] = +x[0, 0] / d
``

2022-01-20 13:18 UTC, closed without merging