Some documentation improvements
odin-lang/Odin pull request #1539
Opened 2022-02-23 05:15 UTC by FancyKillerPanda

I've been working on some of the formatting and content of the documentation. It's far from done but it's a start.

I also changed `//+ignore` to `//+private` as ignore doesn't do anything, which caused some of the procedures from example/internal parts of packages to appear in the docs.

2022-02-23 11:16 UTC, Kelimion commented
You may want to revert [Changed all occurences of //+ignore to //+private.](https://github.com/odin-lang/Odin/pull/1539/commits/d71da1ea05984fcd78624049178b35db0a2e8827)

They're not the same thing and introduced breaking changes as a result.

2022-02-23 11:20 UTC, Kelimion commented on core/container/bit_array/bit_array.odin
> +In: <br>
Please don't add HTML tags to documentation. Gross.
If they're needed on the output side, that ought to be handled by the documentation generator.

2022-02-23 14:20 UTC, gingerBill commented on core/container/bit_array/bit_array.odin
> +In: <br>
Please don't use `<br>` within the documentation. The docs need to be readable from the test and from `odin doc` which is a terminal viewer.

We should use a better markup to make it clear that it is a list below

2022-02-23 14:21 UTC, gingerBill commented on core/encoding/json/doc.odin
> +<pre><code class="hljs" data-lang="json">
No HTML tags. 

This is better solved with the documentation generation tool rather than just hacking it in.

2022-02-23 14:22 UTC, gingerBill commented on core/path/filepath/path.odin
> +// Examples: <br>
No HTML tags

2022-02-23 14:22 UTC, gingerBill commented on core/path/filepath/path_unix.odin
> +// Examples: <br>
No HTML tags.

2022-02-23 14:22 UTC, gingerBill commented on core/path/filepath/path_windows.odin
> +// Examples: <br>
No HTML tags.

2022-02-23 14:22 UTC, gingerBill commented on core/path/filepath/walk.odin
> +// The sole exception is if `skip_dir` is returned as `true`: <br>
No HTML tags. Need better list semantics for the generator.

2022-02-23 14:23 UTC, gingerBill requested changes
No HTML tags, the generator's markup language needs improving instead.

2022-02-24 00:40 UTC, FancyKillerPanda commented
I'm closing this as discussed with Jeroen. I'll try working on improving the doc generator so that we can use better formatting here without HTML tags. I'll keep this code around though so I can later put it back (with modifications to remove the bad bits :) ).

2022-02-24 00:40 UTC, closed without merging