Fix assert in issue #1555 and improve error messages with 'using _'
odin-lang/Odin pull request #2128
Opened 2022-10-14 07:43 UTC by Lperlind

Issue #1555 was caused by blank identifiers not being present in the module values map.
Since `using _` was illegal in a procedures body I extended the check for procedure parameters to be the same.

Additionally for consistency I made `foo :: struct(using _: ^Bar) `have the same error message as `using _`
Being: `'using' is now allowed with the blank identifier '_'`

Since empty identifiers in a procedure get a blank identifier added for them, I also added a check for the character at the tokens location to be `_`. This produces a clearer message in statements like `foo :: struct(using ^Bar)` which also triggered the assert in #1555. Being: `'using' with a procedure parameter requires an identifier`
I didn't really know how to go around identifying if this was an inserted `_` or if it was present in the source code.
Change as needed.

Tested the below which no longer asserts
```
package main

Foo :: struct {
    value: int,
}

bar0 :: proc(using _: ^Foo) { // <- error 'using' is now allowed with the blank identifier '_'
}

bar1 :: proc(using ^Foo) { // <- error: 'using' with a procedure parameter requires an identifier
}

main :: proc(){
    using _  // <- error 'using' is now allowed with the blank identifier '_'
    bar0(&{})
    bar1(&{})
}
```

2022-10-14 11:22 UTC, gingerBill requested changes

2022-10-14 11:49 UTC, Lperlind commented on src/check_decl.cpp
> +					if (file_bytes[e->token.pos.offset] == '_') {
A blank identifier is added, from my short time looking around. I didn't know how to know if it was inserted or if the user actually wrote _.

Either you could have the same error message for both cases or there's a better way to know if there is no _ character.

2022-10-14 23:56 UTC, elusivePorpoise commented
`using _` is allowed in structs so the error messages should me more specific.

2022-10-15 06:09 UTC, gingerBill commented on src/check_decl.cpp
> +					if (file_bytes[e->token.pos.offset] == '_') {
Just have the same error message.

2022-10-15 08:51 UTC, Lperlind commented
Changed to generic error message.
Made the statement case more specific to not be confused with `using _` inside a struct

2022-10-17 10:45 UTC, merged