Updated bindings and libs for Raylib 5.0
odin-lang/Odin pull request #2964
Opened 2023-11-19 18:46 UTC by seanarooni

2023-11-19 23:20 UTC, flysand7 requested changes
Could you also please add `RAYLIB_VERSION_MAJOR`, etc constants to the package and bind the `raylib_version` symbol from `rcore.c`? They don't really make it public but it's kind of essential.

2023-11-19 23:20 UTC, flysand7 commented on vendor/raylib/rlgl.odin
> +	rlEnablePointMode		 :: proc() --- 							 // Enable point mode
Please use tabs for indentation and **spaces** for alignment. There's a few cases of you using tabs to align things which looks off if you set the tab size to 8.

2023-11-22 12:49 UTC, gingerBill commented on vendor/raylib/raylib.odin
> +    params: 	[4]c.int, 			// Event parameters (if required) ---
Please use tabs for indentation and spaces for alignment.

2023-11-22 20:24 UTC, Kelimion commented
Are these compiled with JPEG support? The current libraries don't appear to be, and it would be great to have. It's apparently not a default when building Raylib.

2024-01-03 18:32 UTC, merged